version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres

    ports:
      - "5432:5432"

    environment:
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
        - POSTGRES_DB=gerenciador_tarefas
    #volumes:
    #  - ./data/postgres:/var/lib/postgresql/data


